package org.firstinspires.ftc.teamcode.game

object RelicRecoveryConstants {
    const val LEADING_FRONT_CRYPTO_BOX_DISTANCE = 49.0
    const val CENTER_FRONT_CRYPTO_BOX_DISTANCE = LEADING_FRONT_CRYPTO_BOX_DISTANCE + 17.0
    const val TRAILING_FRONT_CRYPTO_BOX_DISTANCE = CENTER_FRONT_CRYPTO_BOX_DISTANCE + 18.0

    const val LEADING_SIDE_CRYPTO_BOX_DISTANCE = 111.0
    const val CENTER_SIDE_CRYPTO_BOX_DISTANCE = LEADING_SIDE_CRYPTO_BOX_DISTANCE + 19.0
    const val TRAILING_SIDE_CRYPTO_BOX_DISTANCE = CENTER_SIDE_CRYPTO_BOX_DISTANCE + 18.0
}